### ISSUE TITLE
factory model with Grafana

### ISSUE THREAD

**Issue by Productivix** [Spruik/Libre#11]
hi , can you just tell me please how you do the Grafana model of factory : https://github.com/Spruik/Libre/raw/master/docs/equipment.png
thanks

**Comment by tomhollingworth** [comment]
The image or the data structure?

**Comment by Productivix** [comment]
hi Tom , thanks for follow up . I have the data structure, I mean how to get the display from the data and from the dashboard the master can generate the data ? thks !

**Comment by tomhollingworth** [comment]
It's done via the Libre-Equipment-CRUD-Tree-Chart-Panel. See https://github.com/Spruik/Libre-Equipment-CRUD-Tree-Chart-Panel

**Comment by Productivix** [comment]
ok , I will have a look , but i do not want any docker. thanks
