### ISSUE TITLE
Installation for win 32bit

### ISSUE THREAD

**Issue by asimakos** [Spruik/Libre#12]
Hello!

Is it possible to run this application on Windows 32 bit environment? I have already installed postgresql, but I can not find somewhere grafana (win 32bit) and afterwards proceed with the installation instructions for Libre. Any idea?

That would help me a lot!
Regards

**Comment by tomhollingworth** [comment]
Unfortunately not, Grafana only provide 64 bit installs on windows environment. You could try and compile some of components for 32 bit see [Grafana](https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md#build-grafana), [InfluxDB](https://github.com/influxdata/influxdb/blob/master/CONTRIBUTING.md#build-influxd-with-make) and [PostgREST](https://github.com/PostgREST/postgrest)
